navikt/isdialogmote

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/CronjobModule.kt
- src/main/kotlin/no/nav/syfo/client/ObjectMapperConfig.kt
- src/main/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjob.kt
- src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodClient.kt
- src/main/kotlin/no/nav/syfo/cronjob/leaderelection/LeaderPodDTO.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Create intiial setup of cronJob that creates a cronjob and the job is only performed by the pod that is the leader.
The cronjob starts after an initial delay and then run periodically according to an interval delay.
Leader election is performed by getting current leader pod from NAIS and comparing it to self.
If an exception is caught in the cronjob, then isAlive and isReady is set to false and the application will restart.
> Create initial CronJob setup

- src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmoteTidSted.kt
Latest DialogmoteTidOgSted is the one that has been created most recently, i.e. the one with the max createdAt, not the max tid.
> Fix dialogmoteTidSted.latest function

- src/main/kotlin/no/nav/syfo/dialogmote/domain/Dialogmote.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt
- src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt
- src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/domain/ArbeidstakerVarselDTO.kt
- src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Create a new data transfer object for transering information to Arbeidstaker in ArbeidstakerVarselAPI. 
The new DTO contains relevant information from DialogmotedeltakerArbeidstakerVarsel plus information from DialogmoteTidOgSted and the virksomhetsnummer of DialogmotedeltakerArbeidsgiver.
> Create separate DTO for ArbeidstakerVarselAPI

- src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
Lager et repeatable script for å styre tilgang til nye tabeller etter hvert som de lages. 
Scriptet kan oppdateres og flyway vil kjøre det hver gang checksum'en endres.
Scriptet kan evnt. også brukes til å fjerne rettigheter og legge inn nye mer begrensede rettigheter.
> Repeatable migration for å styre grants til tabeller

- .github/workflows/kafka.yaml
- .nais/kafka/dev.json
- .nais/kafka/prod.json
- .nais/kafka/statusendring.yaml
- README.md
- Create Kafka topic with kafkarator(Aiven Kafka) for dialogmote-statusendring for usage in NAV statistikk.
- Create Github action workflow for handling deploy of Kafka topic.
- Update README with a section about kafka.
> Create kafka topic for status endring

- src/main/kotlin/no/nav/syfo/dialogmote/domain/DocumentComponentDTO.kt
- src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmoteApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Endre til liste med tekster i DocumentComponentDTO for å kunne støtte signaturer og andre tekst-bolker der det er ønske om å ha mindre linjeavstand enn det blir mellom paragrafer.
> Endrer til liste med tekster i DocumentComponentDTO

- src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt
Legge på orderby i query slik at informasjon om nyeste møte kommer først i responsen som bruker av esyfo.
> Sikre riktig ordning i respons til arbeidstaker

- src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql
- src/main/resources/db/migration/V4_8__create_table_mote_referat.sql
Dette er ment som et utkast til hvordan referatet representeres i databasen.
Jeg er usikker på om vi trenger flagg for sjekkboksene som er spesifisert i MVP'en - disse styrer bare hvilke standardtekster som blir med i document-dto'en. Vi kunne eventuelt utvide DocumentComponentDTO med et optional key-felt som kan gjøre det enklere for frontend å bestemme hvilke sjekkbokser som ble valgt.
> Databasetabeller for referat

- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/AvlysDialogmoteApiSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/FerdigstillDialogmoteApiSpek.kt
Siden vi har så mange eksterne avhengigheter (feks publisering til MQ/Kafka), så kan vi ikke tillate at tilstanden til møtet endrer seg dersom det har blitt avlyst eller ferdigstilt.
> Validering av tilstandsendringer

- src/main/kotlin/no/nav/syfo/dialogmote/domain/DocumentComponentDTO.kt
- src/test/kotlin/no/nav/syfo/dialogmote/FerdigstillDialogmoteApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
For å gjøre det enklere for esyfo-app'ene å vise relevante linker knyttet til standardtekster i referatet, legger vi til et optional key-felt i DocumentComponentDTO - dvs en nøkkel som ikke endrer seg selv om innholdet i standardteksten skulle bli endret.
> Nytt key-felt i DocumentComponentDTO

- src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt
Vi ser en del 403-feil fra syfoperson i loggene til isdialogmote. Tror vi kan få færre forekomster av det ved å unngå å kalle syfoperson for å sjekke adressebeskyttelse hvis vi allerede har funnet ut at veilederen ikke har tilgang til personen.
> Unngå kall til syfoperson for veiledere som ikke har tilgang til person

- src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt
- src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Unngå at lestdato oppdateres og nye varsler sendes ut ved multiple kall til api-post-tjenesten for å sette et varsel eller referat som lest.
Kan endre til å lage en feil, men synes i utgangspunktet ikke det er så viktig i dette tilfellet.
> Ikke oppdatere lestdato ved multiple api-kall

- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/person/PersonMetric.kt
- src/main/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClient.kt
Et nytt forsøk på å løse problemet med sporadiske 500-feil. Lurer på om det skyldes at kall til syfoperson timer ut.
> Øke http-timeout og timer for kall til syfoperson-adressebeskyttelse.

- src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt
Fant et annet sted der vi gjør kall til syfoperson selv om veileder mangler tilgang til personen.
> Unngå kall til syfoperson for veiledere som ikke har tilgang til person (igjen)

- src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt
- src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt
- src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/domain/PdfContent.kt
- src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Her er et forslag til det endepunktet for å hente pdf vi snakket om. I første omgang skal det brukes for å hente pdf for referat, men det er så lite ekstra som skal til for å gjøre det generelt - så det som er foreslått her kan brukes til å hente pdf også for innkalling, avlysning og endring av tid/sted.
> Endepunkt for å hente ut pdf for arbeidstaker-varsel

- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
Fjerne timeout som ble lagt til i et førsøk på å løse sporadiske 500-feil (hadde ingen effekt)
> Fjerne http timeout

- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Legger til tester som sjekker at http-status blir Forbidden dersom api-kall har token for en annen arbeidstaker enn den som er relatert til dialogmøtet.
> Forbedrer tester for API for arbeidstaker

- src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/DigitalKontaktinfoBolk.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/v1/DialogmoteActionsApi.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/v1/DialogmoteApi.kt
- src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt
Make it easier to find the cause of denied access to updating og creating a Dialogmote. The log message is written as an error because this situation should not occur in production as long as DialogmoteInnkalling is not available for persons that only cannot receive digital notifications.
> Add explicit logging if DigitalVarsel is not allowed

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederVarselService.kt
- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmoteApiSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- src/test/kotlin/no/nav/syfo/testhelper/mock/ModiasyforestMock.kt
Varslingsnøklene er nå definert i varseladmin med tilhørende epost-maler. Parameterene som sendes med er forenklet i forhold til det som brukes fra syfomoteadmin, så de vi trenger nå er navn på nærmeste leder og tidspunkt for dialogmøte.
> Tilpasser servicemelding som sendes via MQ

- .nais/naiserator-prod.yaml
https://doc.nais.io/clusters/migrating-to-gcp/#how-do-i-reach-an-application-found-on-gcp-from-my-application-on-premises
> Ingress som skal gjøre det mulig å nå isdialogmote fra sbs

- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Koden senere i løypa antar at dersom møtet har behandler så har vi med behandler på avlysning/endring og krasjer med NPE hvis ikke. Legger til validering for å gi bedre feilmelding og unngå at varsler potensielt blir sendt ut før det krasjer.
> Validerer at avlysning/endring har behandler når dialogmøte har med behandler

- build.gradle.kts
Bump Kotlin, nimbusjoseJwt, mockk, logback-classic and micrometer to latest version.
> Bump dependencies to latest version

- src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt
- src/main/kotlin/no/nav/syfo/application/exception/ConflictException.kt
- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt
A conflict can occur if multiple users arre trying to change the state of the same Dialogmote at the same tid. In case of such a conflict, throw a ConflictException instead of a generic RuntimeException, and return a http 409 indicating a conflict in the state of the accessed Dialogmote. Then the consuming application can update its state accordingly.
> Convert exceptions to ConflictException

- src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidsgiverVarselQuery.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidstakerVarselQuery.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselQuery.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/ReferatQuery.kt
Så noen eksempler i preprod der dokumenter ble journalført i en annen rekkefølge enn de er opprettet i isdialogmote, og det kan gjøre oversikten i Gosys forvirrende.
> Journalføre dokumenter i samme rekkefølge som de er opprettet

- README.md
- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederVarselService.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederVarselType.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/dinesykmeldte/DineSykmeldteVarselProducer.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/dinesykmeldte/KafkaDineSykmeldteVarselProducerConfig.kt
- src/main/kotlin/no/nav/syfo/brev/narmesteleder/domain/DineSykmeldteVarselDTO.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/MotedeltakerVarselType.kt
- src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt
- src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteEnhetApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/OvertaDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
Nye dine sykmeldte går live på mandag, og vi har ikke klart å få på plass ordentlig løsning for varselutsending enda.
Tanken er at esyfovarsel håndterer utsending, og så kan både MQ-utsending og dine sykmeldte-varsler fases ut fra isdialogmøte.
Men inntil det er på plass må isdialogmote stå for utsending til nye dine sykmeldte.
> Send varsel to new Dine Sykmeldte topic

- .nais/naiserator-prod.yaml
Increase pod memory and minimum number of pods to 3 to handle peak demand.
> Increase resources to handle peak demand

- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
Vi får ganske hyppig
java.lang.RuntimeException: Caught ClosedReceiveChannelException in hasAdressebeskyttelse
Gjør et forsøk på å ta i bruk retry-logikken i ktor 2.0 for å forbedre det.
> Use retry to handle ClosedReceiveChannelException

- src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt
- src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt
Ser ut som denne retry-funksjonaliteten fungerer bra (og i hvert fall ikke gjør noen skade). Så legger det inn sånn at det har effekt for alle klientene i app'en.
> Use retry to handle ClosedReceiveChannelException generally

- src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjob.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MoteStatusEndretQuery.kt
Reduce interval from 60 minutes to 1 minute to provide almost-instant update for consumers of Kafka topic
> Reduce interval of PublishDialogmoteStatusEndringCronjob

- .nais/alerts.yaml
Unngå at vi får en alert når en enkelt pod restartes.
> Alert when no running pods

- .nais/naiserator-prod.yaml
Maybe remove entire toggle after verification by a veileder in prod?
> Enable KODE6 access in prod

- src/main/resources/db/migration/V8_3__add_motesvar_kafka.sql
Add to "varsel" tables for AG/AT, and "varsel_svar" table for behandler.
> Add timestamp for motesvar published on kafka

- src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringService.kt
If we use "now" it will always be shifted by the amount of time it took the cronjob to fetch the statusendring from the database.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Set the time veileder made the statusendring as endringstidspunkt

- .nais/naiserator-prod.yaml
- src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Det har dukket opp et behov for å få lukket et møte uten at det genereres tilhørende varsler, så da bruker vi mekanismen i den nye cronjob'en til dette.
> Lukke moter adhoc

- build.gradle.kts
had to upgrade jackson-datatype-jsr310 separately, as they are not in sync with each other. These upgrades fix medium snyk error: https://cwe.mitre.org/data/definitions/400.html
> Upgrade jackson --> 2.13.4.2

- src/main/kotlin/no/nav/syfo/dialogmote/database/BehandlersvarPublishedToKafkaAtQueries.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselSvarQuery.kt
- src/test/kotlin/no/nav/syfo/cronjob/dialogmotesvar/PublishDialogmotesvarServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
This is to ensure ispersonoppgave don't open a new oppgave after the meeting is ferdigstilt/avlyst.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
> Only publish valid behandlersvar to kafka

- build.gradle.kts
Basert på Snyk:
- CXF `3.5.2` til `3.5.5`: https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHECXF-3168315
- protobuf enforce `3.21.7` : https://security.snyk.io/vuln/SNYK-JAVA-COMGOOGLEPROTOBUF-3167774
I tillegg lagt de i alfabetisk rekkefølge når jeg først var i gang 🤷🏼‍♂️ 
PR nr 400 🥳
> Update cxf, enforce protobuf-java and order versions by name

- src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt
- src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/BehandlersvarPublishedToKafkaAtQueries.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselSvarQuery.kt
- src/test/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselServiceSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/dialogmotesvar/PublishDialogmotesvarServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
Remove concept that a behandler svar can be invalid and put all behandler svar on kafka. This means that a late behandler svar, i.e we recieve it after a meeting is closed, must be handled by the consumer (if it deems it necessary).
The only consumer currently is ispersonoppgave, which means this commit must be merged after it's handled there.
> Do not invalidate a late behandler svar

- src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt
- src/main/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjob.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidsgiverVarsel.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandlerVarsel.kt
- src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt
- src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testhelper/generator/JournalpostRequestGenerator.kt
- src/test/kotlin/no/nav/syfo/testhelper/mock/DokarkivMock.kt
This will be required by dokarkiv 20. december.
If api receives an eksternReferanseId that is already stored, it will return 409 Conflict with the existing JournalPost as body. We want to fail when we get 409 becuase we don't want to journalføre the same varsel more than once. Since 409 gives clientException, the existing client returns null, which is then handled by the cron jobs.
> IS-1867: Add eksternReferanseId to dokarkiv body

- src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClient.kt
- src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivMetric.kt
- src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
- src/test/kotlin/no/nav/syfo/testhelper/mock/DokarkivMock.kt
409 fra Dokarkiv betyr at journalpost allerede er opprettet og vi kan håndtere dette ved å lagre journalpostIden vi får fra responsen.
> IS-1973: Handle 409 conflict from dokarkiv

- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/domain/TildelDialogmoterDTO.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteActionsApiV2.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/TildelDialogmoteApiV2Spek.kt
- Legger til endepunkt som gjør det mulig å tildele en annen veileder dialogmøter
- Et spørsmål er om vi også bør sjekke tilgang til veileder som skal få tildelt møter. I så fall kan det se ut som vi må legge til funksjonalitet i `istilgangskontroll` for å sjekke tilgang basert på en `veilederIdent` og ikke bare token som vi gjør i dag.
> IS-1947: Add endpoint to assign dialogmote to other veileder

- build.gradle.kts
https://nvd.nist.gov/vuln/detail/CVE-2023-44483
> Bump cxf and force safe xmlsec version

- .nais/naiserator-dev.yaml
- .nais/naiserator-prod.yaml
isdialogmote er fjernet fra outbound access policies i [ditt-sykefravaer](https://github.com/navikt/ditt-sykefravaer/pull/964/files) så fjerner inbound her
> Remove access policy

- src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Ref: https://jira.adeo.no/browse/FAGSYSTEM-328214
Her har man fått laget to innkallinger på samme møte. Det ene er ferdigstilt, så lukker det andre.
> IS-2339: Lukker duplikat møte

- src/main/kotlin/no/nav/syfo/janitor/JanitorService.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventConsumer.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventConsumerConfig.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventDTO.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventDeserializer.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventStatusDTO.kt
- src/main/kotlin/no/nav/syfo/janitor/kafka/JanitorEventStatusProducer.kt
- src/test/kotlin/no/nav/syfo/janitor/JanitorServiceSpek.kt
Lager ny PR på å starte opp consumeren i App.kt (krever en del refaktorering/flytting av services som den er avhengig av)
> IS-2241: Setup consumer for janitor event and produce event status

- src/main/kotlin/no/nav/syfo/application/database/Database.kt
Med denne tilpasningen bør vi unngå feil av typen "org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update"
> Use db-isolation leve READ_COMMITTED

- src/main/kotlin/no/nav/syfo/App.kt
- src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt
- src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
- src/main/kotlin/no/nav/syfo/dialogmote/DialogmotestatusService.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmoteStatusEndringDTO.kt
- src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteApiV2.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/repository/MoteRepository.kt
- src/main/kotlin/no/nav/syfo/dialogmote/database/repository/MoteStatusEndretRepository.kt
- src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt
- src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt
- src/test/kotlin/no/nav/syfo/cronjob/dialogmoteoutdated/DialogmoteOutdatedCronjobSpek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/api/v2/motestatusendring/GetDialogmoteStatusEndringApiV2Spek.kt
- src/test/kotlin/no/nav/syfo/dialogmote/database/repository/MoteRepositorySpek.kt
- src/test/kotlin/no/nav/syfo/janitor/JanitorServiceSpek.kt
- src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
Legger til et endepunkt som returnerer en liste med alle statusendringer på dialogmøter for en person, og hvilket møte den endringen tilhørte.
Litt frem og tilbake her om man skal vise tidspunkt og sted for møtet, og hva det evt har blitt endret til og fra. Det kan bli mye logikk for å få til noe vi ikke helt vet om de trenger. Jeg tenkte vi derfor bare kunne starte med dette, så blir formatet i frontend ish:
3. nov | X999999 avlyste et dialogmøte (evt "avlyste dialogmøtet")
2. nov | X999999 endret tid eller sted på dialogmøtet (men sier ikke noe om hva som ble endret til)
28. okt | X999999 kalte inn til dialogmøte
> IS-1879: Add api for dialogmote statusendringer
