src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteApi.kt, src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmotePlanlagtApiSpek.kt
Create Dialogmote based on a UUID of a PlanlagtMote to be retrieved from Syfomoteadmin
=> Add endpoint and test for creating Dialogmote

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/OIDC.kt, src/main/kotlin/no/nav/syfo/application/cache/RedisStore.kt, src/main/kotlin/no/nav/syfo/client/HttpClientCommon.kt, src/main/kotlin/no/nav/syfo/client/ObjectMapperConfig.kt, src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClient.kt, src/test/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClientSpek.kt, src/test/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClientSpek.kt
Lagt til caching av kontaktinfo-objekt og samtidig refaktorert til gjenbrukbar jackson object mapper.
=> Cache kontaktinfo

.github/workflows/redis.yaml, .nais/redis-config.yaml, .nais/redisexporter.yaml, README.md
Basert på https://doc.nais.io/persistence/redis/index.html#redis-metrics
=> Lagt til redisexporter for metrics

src/main/resources/db/migration/V4_4__grant_to_cloudsqliamuser.sql
Gjøre det mulig å aksessere databasen fra utviklermaskin og naisdevice via cloudsqlproxy
=> Gjøre det mulig å aksessere databasen fra utviklermaskin via cloudsql

src/main/resources/db/migration/V4_7__create_table_motedeltaker_arbeidsgiver_varsel.sql
Create table for all varsler/brev sent to Motedeltaker of type Arbeidsgiver
=> Create base table MOTEDELTAKER_ARBEIDSGIVER_VARSEL

src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/AvlysDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/FerdigstillDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/GetDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/GetDialogmoteEnhetApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/GetDialogmoteWithMissingValuesApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmotePlanlagtApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmoteTidStedApiSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/PostDialogmoteWithMissingValuesApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestKafka.kt, src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Use resuable function to create embedded Kafka environment to avoid repetition.
=> Refactor embedded Kafka environment

src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/Dokument.kt, src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerVarselJournalforingService.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/varsel/MotedeltakerVarselType.kt, src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
All types of MotedeltakerVarsel should be sent to Journalforing. This is a mandatory requirement.
=> Journalfor MotedeltakerVarsel of type AVLYST and NYTT_TID_STED

src/main/kotlin/no/nav/syfo/dialogmote/domain/Dialogmote.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/domain/ArbeidstakerVarselDTO.kt
Add deltakerUuid to ArbeidstakerVarselDTO to simplify grouping of related elementents in the list. The grouping is based on the uuid of the Deltaker that received the Varsel
=> Add deltakerUuid to ArbeidstakerVarselDTO

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/DialogmoteActionsApi.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmoteDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/NewReferatDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/ReferatDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ReferatQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMote.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PReferat.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Dialogmote.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/NewReferat.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/test/kotlin/no/nav/syfo/dialogmote/FerdigstillDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Modell og api-tilpasninger for referat fra dialogmøte.
Pdf-generering og journalføring av pdf kommer etterpå.
Tilpasninger av api for esyfo kommer også etterpå.
=> Modell og api-tilpasninger for referat

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt
Refactor logic for creating MoteStatusEndring to prepare for producing MoteStatusEndring to Kafka topic.
=> Refactor logic for MoteStatusEndring

src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidstakerVarselQuery.kt, src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt, src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Fant en bug som gjorde at varselet ikke ble funnet når lestdato skulle settes.
=> Bugfix setting av lestdato i ArbeidstakerVarselApi

src/main/kotlin/no/nav/syfo/application/cache/RedisStore.kt
Hvis vi ikke får kontakt med redis, logg feilen og returner null
Hvis vi ikke får lagret, logg feilen og fortsett som før.
=> Handle ConnectionException in redis

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/ReferatDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidsgiverVarselQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidstakerVarselQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ReferatQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PReferat.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Dialogmote.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/main/kotlin/no/nav/syfo/varsel/MotedeltakerVarselType.kt, src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt, src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselService.kt, src/main/kotlin/no/nav/syfo/varsel/narmesteleder/NarmesteLederVarselService.kt, src/main/kotlin/no/nav/syfo/varsel/narmesteleder/NarmesteLederVarselType.kt, src/main/resources/db/migration/V5_2__referat_lest.sql, src/test/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApiSpek.kt
Referat skal komme med i responsen til esyfo (på linje med innkalling, avlysning og endring av tid/sted).
Skal være mulig å registrere et referat som lest av arbeidstaker (på samme måte som innkalling).
=> Referat i respons fra ArbeidstakerVarselApi

.nais/kafka/statusendring.yaml
Grant dvh-syfodm2-konsument read access to Kafka topic for DialogmoteStatusEndring for use in statistics
=> Grant new read access to topic StatusEndring

src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt
Forsøker å finne ut av 500-feil som dukker opp ganske hyppig i produksjon. 
Er ikke sikkert dette bringer oss så mye videre, men i alle fall nyttig å ha med logging her som inkluderer stack trace tenker jeg.
=> Forbedre logging

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt, src/test/kotlin/no/nav/syfo/dialogmote/FerdigstillDialogmoteApiSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Oppdatere tildeltVeilderIdent på møtet dersom referat lages av annen bruker enn den som lagde innkallingen
=> Oppdatere tildeltVeilderIdent på møtet om nødvendig

src/main/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClient.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt
Dette dreier seg fortsatt om å finne ut av de sporadiske 500-feilene vi ser i produksjon. 
Inspirert av denne: https://medium.com/juullabs-engineering/the-tale-of-the-misleading-coroutine-stacktrace-29fc6203df04
=> Catch-rethrow ClosedReceiveChannelException for å få bedre stack trace

src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/ReferatJournalforingService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PReferat.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/ArbeidstakerBrev.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/main/kotlin/no/nav/syfo/varsel/arbeidstaker/ArbeidstakerVarselApi.kt
Refaktorerer ArbeidstakerVarselApi for å redusere duplisert kode. Tentativ introduksjon av begrepet Brev (til erstatning for Varsel).
=> Refaktorerer api for arbeidstaker

src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerVarselJournalforingService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt
... og vi unngår å gjøre first() på lister andre steder i koden.
=> Refaktorerer slik at databaselaget sjekker at møtedeltaker er unik

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/OvertaDialogmoterDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteActionsApiV2.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteEnhetApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/OvertaDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfobehandlendeenhetMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/VeilederTilgangskontrollMock.kt
- Laget actions api v2 for overta dialogmøter
- Slettet noen ubrukte/duplikate metoder og gjort noen private i DialogmoteService / DialogmoteTilgangService
=> actions api v2 for overta moter

build.gradle.kts, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/api/PrometheusApi.kt, src/main/kotlin/no/nav/syfo/application/api/authentication/ApiFeature.kt, src/main/kotlin/no/nav/syfo/client/person/PersonMetric.kt, src/main/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClient.kt, src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClient.kt, src/main/kotlin/no/nav/syfo/client/person/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/metric/Metrics.kt
Med denne konfig'en skal vi få ut alle metric'ene vi har fra før, og i tillegg blant annet 
ktor_http_server_requests_seconds_count
der det vil være mulig å filtrere på status (200, 4xx, 5xx).
=> Bruke ktor micrometer feature

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteActionsApiV2.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt
Add version 2 of TidSted-endpoint in DialogmoteActionsAPI supporting AzureAD V2
=> Add version 2 of TidSted-endpoint

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteActionsApiV2.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt
Add Version 2 of endpoints for Avlys and Ferdigstill in DialogmoteActionsAPI supporting AzureAD v2
=> Add version 2 of endpoints Avlys and Ferdigstill

.nais/naiserator-dev.yaml
Gjør dette i første omgang bare for dev, så kan vi se om det løser aksessproblemet.
=> Ingress som skal gjøre det mulig å nå isdialogmote fra sbs

src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetClient.kt, src/main/kotlin/no/nav/syfo/client/behandlendeenhet/BehandlendeEnhetMetric.kt, src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClient.kt, src/main/kotlin/no/nav/syfo/client/dokarkiv/DokarkivMetric.kt, src/main/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClient.kt, src/main/kotlin/no/nav/syfo/client/narmesteleder/NarmestelederMetric.kt, src/main/kotlin/no/nav/syfo/client/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/client/pdfgen/PdfgenMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjob.kt
Glemte noen tilpasninger da jeg gjorde overgangen til Micrometer.
=> Tilpasser flere metrics til micrometer

src/main/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApi.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevApi.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestDatabase.kt
Viste seg at vi klarte å lage bugs her som ikke ble fanget opp av testene fordi moteid og motedeltakerid i databasen tilfeldigvis matchet. Har endret testdb-oppsettet slik at det opprettes noen dummy-rader først.
=> Bugfix brev-api

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2KRREnabledSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfobehandlendeenhetMock.kt
Har laget toggle slik at ny funksjonalitet er skrudd av i første omgang.
=> Tillate dialogmøte for KRR-bruker

src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt
Refaktorering for å unngå kodeduplisering når kontaktinfo skal hentes andre steder i koden.
=> Refaktorering for å unngå kodeduplisering

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Når vi enabler KRR må vi sjekke om arbeidstakeren aksepterer digital varsling hver gang vi skal sende et varsel.
=> Set digital varsling

src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmoteCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/DialogmoteCronjobRunner.kt, src/main/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjob.kt, src/main/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjob.kt, src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjobSpek.kt
Refaktorert litt som forberedelse til ny cronjob for å distribuere journalposter til arbeidstakere som ikke skal varsles digitalt
=> Refaktorert litt duplisert cronjob-kode

src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidstakerVarselQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ReferatQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt
Testkode for dette kommer sammen med neste PR fra Anders.
=> Queries for å finne brev som skal sendes fysisk

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/VeilederTilgangskontrollMock.kt
Update to Syfo-tilgangskontroll ClientID provisioned by azurerator
=> Update endpoint and clientId of syfo-tilgangskontroll

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/client/dokarkiv/domain/JournalpostRequest.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonResponse.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlRequest.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/main/kotlin/no/nav/syfo/metric/Metrics.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt, src/main/resources/pdl/hentPerson.graphql, src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/PdlMock.kt
Må vente på denne før vi merger:
https://jira.adeo.no/plugins/servlet/desk/portal/541/FAGSYSTEM-184103
=> Bruke PDL til å hente navn for journalføring

.nais/naiserator-dev.yaml
Foreslår at vi lar toogle for å tillate varsel med fysisk brev være på i testmiljøet
=> Teste sending av fysisk brev

src/main/kotlin/no/nav/syfo/client/journalpostdistribusjon/JournalpostdistribusjonClient.kt
Ref: https://github.com/navikt/isproxy/pull/16
=> Tilpasser path for dokdist (via isproxy)

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevApi.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederTilgangService.kt
Fix loophole giving a NarmesteLeder access to more information that is allowed. Some refactoring of the access control to NarmesteLederAPI is also done for readability and reuseability
=> Fix security loophole in access control for NarmesteLederApi

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmoteTidSted.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt
Ref diskusjon på Slack: https://nav-it.slack.com/archives/GGX6MF9S8/p1632920018001800
=> Opprette brev for avlyste møter med tidspunkt tilbake i tid

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/api/PodApi.kt, src/main/kotlin/no/nav/syfo/application/api/PrometheusApi.kt, src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt
Ref avsnittet "prod-gcp ingresses" her: https://doc.nais.io/clusters/gcp/
=> Unngå at interne endepunkt er eksponert på internett

src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerVarselDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandler.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandlerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/BehandlerType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandler.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandlerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/NewDialogmote.kt
Kommer api og tester i en eller flere egne PR'er
=> Modell for møtedeltaker-behandler

src/main/resources/db/migration/R__grant_to_cloudsqliamuser.sql, src/main/resources/db/migration/V5_8__create_isyfoanalyse_user.sql
Tilpasninger slik at det blir mulig å gjøre data-analyse basert på isdialogmote-db, ref: 
https://nav-it.slack.com/archives/G012X72TL12/p1635777336036800
=> Grant to isyfo-analyse

src/main/kotlin/no/nav/syfo/App.kt
Dette er et forsøk på å gjøre main-metoden litt mer forståelig og tilrettelagt for nye ting. 
Samt at koden slik den var treffer minste en forekomst av dette: 
API marked with this annotation is not intended to be used by end users unless a custom server engine implementation is required
=> Refactor main method

src/main/kotlin/no/nav/syfo/client/pdfgen/PdfGenClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsdialogmotepdfgenMock.kt
Forenkling av pdf-generering
Må ikke merges før denne har blitt merget inn: 
https://github.com/navikt/isdialogmotepdfgen/pull/12
=> Simplify pdf-gen

src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt, src/test/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClientSpek.kt
Fix error in production with usage of OBO-token in requests to PDL
=> Only make request to PDL with AzureAD system token

.nais/kafka/statusendring.yaml
Grant team-dialog with application sf-dialogmote access to topic isdialogmote-dialogmote-statusendring
=> Add new consumer of topic Statusendring

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
OBS: Ikke merge til prod enda! 
Ruller snart ut Dialogmøte sykmeldt til GCP, så må endre URL her etter det :)
=> Change Dialogmote URL to GCP

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/BackgroundTask.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/kafka/Kafka.kt, src/main/kotlin/no/nav/syfo/brev/arbeidstaker/brukernotifikasjon/KafkaBrukernotifikasjonerConfig.kt, src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/BehandlerDialogmeldingProducer.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaBehandlerDialogmeldingConfig.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaBehandlerDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaDialogmelding.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaDialogmeldingConfig.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaDialogmeldingDeserializer.kt, src/main/kotlin/no/nav/syfo/brev/behandler/kafka/KafkaModule.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/statusendring/KafkaDialogmoteStatusEndringConfig.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Avhengig av topic som lages i https://github.com/navikt/padm2/pull/67
=> Setup processing of dialogmeldinger from kafka-topic

src/main/resources/db/migration/V6_1__create_table_motedeltaker_behandler_varsel_svar.sql
Iht veiledning for bruk av dialogmeldinger kan behandler svare:
1 Ja, jeg kommer (m/ valgfritt tekstsvar)
2 Jeg ønsker nytt møtetidspunkt (m/ obligatorisk tekstsvar)
3 Jeg kan ikke komme / begrunnelse for manglende oppmøte (m/ obligatorisk tekstsvar)
Svar skal kunne gis flere ganger på samme forespørsel (varsel)
=> Databasetabell for svar fra behandler

src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/Kodeverk.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerVarselDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerVarselSvarDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselSvarQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandlerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandlerVarselSvar.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmoteSvarType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandlerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandlerVarselSvar.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/MotedeltakerVarselType.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2BehandlerSvarSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt
Domain and persistence model for behandler-varsel-svar. Extended DTOs. Add test.
=> Queries for creating and getting behandler varsel svar (innkalling)

src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederVarselService.kt
Do not send empty values to MQ-queue
=> Fix WSServicemeldingMedKontaktinformasjon to Narmeste Leder

src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselQuery.kt
Kan ikke anta at alle dialogmeldinger av type svar vi konsumerer har conversationRef og parentRef som kan parses som UUID
=> Endrer conversationRef og parentRef til String i DialogmeldingSvar

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/NewDialogmoteDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandler.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandler.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/NewDialogmote.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Slik at vi kan validere at svar fra behandler på innkalling har riktig behandler-fnr.
=> Lagre personident på motedeltaker behandler

src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/DialogmeldingConsumerService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselQuery.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaDialogmeldingDTOGenerator.kt
Ved mottak av dialogmelding fra behandler med svar på innkalling bør vi også sjekke at behandler-personident stemmer i fallback-spørringen som finner siste varsel av en gitt type for arbeidstakeren.
=> Sjekk behandler-personident når vi finner varsel for svar

src/main/kotlin/no/nav/syfo/client/veiledertilgang/VeilederTilgangskontrollClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/tilgang/DialogmoteTilgangService.kt, src/main/kotlin/no/nav/syfo/util/PipelineUtil.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/VeilederTilgangskontrollMock.kt
Reuse access control for personList in access control for a single person.
=> Simplify access control for Veileder

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/client/journalpostdistribusjon/JournalpostdistribusjonClient.kt, src/main/kotlin/no/nav/syfo/client/journalpostdistribusjon/JournalpostdistribusjonMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/test/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjobSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/DokdistFordelingMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsproxyMock.kt
Bruker Azure system-token som beskrevet [her](https://confluence.adeo.no/display/BOA/Distribuere+dokument+til+bruker)
=> Kaller dokdist direkte for distribusjon av journalpost som fysisk brev

src/main/kotlin/no/nav/syfo/dialogmote/api/domain/NewDialogmoteDTO.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteEnhetApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Vi setter tildelt enhet på dialogmøte = behandlende enhet for arbeidstakeren
=> Fjerner ubrukt felt tildeltEnhet på NewDialogmoteDTO

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/DialogmotedeltakerBehandlerDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/domain/NewReferatDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandler.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerBehandler.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Oppdatere MotedeltakerBehandler deltatt/mottar referat ved mellomlagring og ferdigstilling. Send varsel med referat til behandler bare dersom behandler skal motta referat.
=> Model, query and service logic for behandler deltatt/mottar referat

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/altinn/AltinnClient.kt, src/main/kotlin/no/nav/syfo/client/altinn/AltinnMelding.kt, src/main/kotlin/no/nav/syfo/client/altinn/AltinnMetric.kt, src/main/kotlin/no/nav/syfo/client/altinn/AltinnUtil.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteActionsApiV2.kt, src/main/kotlin/no/nav/syfo/dialogmote/api/v2/DialogmoteApiV2.kt, src/test/kotlin/no/nav/syfo/client/altinn/AltinnUtilSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiModule.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsoppfolgingstilfelleMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfobehandlendeenhetMock.kt
Remove Boolean return type from DialogmoteService functions.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
Co-authored-by: Kaja Kvinge Akselsen <kaja.kvinge.akselsen@nav.no>
=> Differentiate Altinn texts based on MotedeltakerVarselType

src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingMetric.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingDTO.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaDialogmeldingDTOGenerator.kt
Ref: https://trello.com/c/YmnWSTbc
=> Registrere svar selv om foresporseltype mangler

src/main/kotlin/no/nav/syfo/brev/domain/BrevType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidsgiverVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidstakerVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/MotedeltakerVarselType.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt
Nytt forsøk: Etter en diskusjon med Erik ble vi enige om at det ryddigste er å skille ut et eget kodeverk for brevtype i selvbetjenings-api'ene.
=> Egen brevtype for endret referat

.nais/naiserator-prod.yaml
https://nav-it.slack.com/archives/C8MU0M6L8/p1651735467281779
=> Switch to MQ high-availability hostname

.nais/naiserator-prod.yaml
This reverts commit 9d637f8951ead1cf9c4691e4139c527ebe0bdeb8.
=> Revert "Switch to MQ high-availability hostname (#298)"

src/main/kotlin/no/nav/syfo/application/database/Database.kt
Vi fikk en ny "krasj" i dag, så ustabilitetsproblemet er ikke løst. Forsøker å øke antall connections litt, og fikse slik at vi får ut metrics.
=> Increase db-pool and fix db-metrics

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/altinn/AltinnMelding.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/test/kotlin/no/nav/syfo/client/altinn/AltinnUtilSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt
Include name and fnr when sending møtebehov varsel to Altinn
=> feat: include name and fnr in title when sending dialogmote notification to Altinn

src/main/resources/logback.xml
Redusere støy i loggen fra Kafka
=> Reduce Kafka-logging

src/main/kotlin/no/nav/syfo/client/journalpostdistribusjon/JournalpostdistribusjonRequest.kt
Ref https://nav-it.slack.com/archives/C6W9E5GPJ/p1651825340333899
=> New required fields in distribuerJournalpost

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Aksess fra flex-gateway har fungert uten dette pga en nais-bug.
Ref https://nav-it.slack.com/archives/C5KUST8N6/p1654846204764059
=> Add missing access policy

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Var litt konfig som forsvant i en merge conflict
=> Add missing access tokenx config

src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt
This reverts commit b9cbfb5aad01f843d9892c605daff68dbc0aa382.
Det ser ut til at Altinn-sending fungerer igjen.
=> Revert "Don't send copy to Altinn when user has leader (#332)"

build.gradle.kts, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederAccessService.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevApi.kt, src/main/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClient.kt, src/main/kotlin/no/nav/syfo/client/tokendings/TokendingsClient.kt, src/main/kotlin/no/nav/syfo/client/tokendings/TokendingsClientMetric.kt, src/main/kotlin/no/nav/syfo/client/tokendings/TokenendingsToken.kt, src/main/kotlin/no/nav/syfo/client/tokendings/TokenendingsTokenDTO.kt, src/test/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClientSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/ExternalMockEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/JWTUtils.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/NarmesteLederMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/TokendingsMock.kt
Må merges *etter* at denne har blitt merget: https://github.com/navikt/isnarmesteleder/pull/56
=> Use tokenx when calling isnarmesteleder

build.gradle.kts
Dette bør fikse en del snyk-issues
=> Bump Confluent

src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfellePersonDTO.kt, src/test/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfellePersonDTOSpek.kt
Hvis flere tilfeller har samme startdato, legger vi det med senest sluttdato først.
=> Improve sorting of oppfolgingstilfelle

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/Oppfolgingstilfelle.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt
Omtrent revert av "Turn of Dialogmoteinnkalling for persons with inactive Oppfolgingstilfelle (#250)" 14/02-2022.
Fjerning av tilfelle helt må skje i neste omgang, siden vi da må kvitte oss med avhengigheter til både DB og kafka.
=> Allow creation of dialogmote for innbygger with inactive tilfelle

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteStatusEndretQuery.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsoppfolgingstilfelleMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfobehandlendeenhetMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/VeilederTilgangskontrollMock.kt
Sett dato langt tilbake i tid som tilfelleStart i de tilfelle hvor innbygger ikke har noen nåværende eller tidligere oppfølgingstilfeller.
=> Allow no oppfolgingstilfelle for innbygger when creating dialogmote

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederVarselService.kt, src/main/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/narmesteLederRevarsel/ResendNarmesteLederVarselCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ResendVarselQuery.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Kun resend varsler som ikke er lest.
=> Add cronjob for resending varsel to NL from a given time frame

src/main/kotlin/no/nav/syfo/client/person/kontaktinfo/DigitalKontaktinfoBolk.kt, src/test/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClientSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/KrrMock.kt
Viser seg at denne dto'en har endret seg, så det blir en deserialiseringsfeil i noen sjeldne tilfeller.
=> Tilpasser dto fra DKIF

.nais/kafka/dialogmotesvar.yaml
=> Add dialogmotesvar kafka topic

src/main/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClient.kt
Fant denne bug'en i forbindelse med at den samme koden tas i bruk i isoppfolgingstilfelle
=> Bugfix: must filter before the list is cached

.github/workflows/kafka.yaml
=> Remove illegal spaces in yaml file

.nais/kafka/statusendring.yaml, .nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobMetric.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmoteStatus.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Oppsett av cronjob - ingen funksjonell endring intendert i denne omgang.
=> Cronjob for lukking av dialogmoter

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederAccessService.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevApi.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfellePersonDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Dialogmote.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/DialogmotedeltakerArbeidsgiverVarsel.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/NarmesteLederBrev.kt, src/main/kotlin/no/nav/syfo/dialogmote/domain/Referat.kt, src/main/kotlin/no/nav/syfo/util/DateUtil.kt, src/main/kotlin/no/nav/syfo/util/RequestUtil.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederAccessServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsoppfolgingstilfelleMock.kt
=> add 4 months or oppfolgingstilfelle start date filter for NL brev

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotestatusService.kt
Må ekstrahere noen tjenester for å oppdatere status fra DialogmoteService.
=> Dialogmoteservice refaktorering

.nais/naiserator-dev.yaml, src/main/kotlin/no/nav/syfo/client/oppfolgingstilfelle/OppfolgingstilfelleClient.kt, src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotestatusService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmoteoutdated/DialogmoteOutdatedCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteDTOGenerator.kt
Enabled i preprod, ikke i prod.
=> Cronjob updates to status LUKKET

src/main/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApi.kt, src/main/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevApi.kt, src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt
Brev fra lukkede møter skal ikke være med i responsen på selvbetjeningsapi'ene.
=> Filtrer brev fra møter med status LUKKET

.github/workflows/kafka.yaml
=> fix typo dev --> prod in kafka.yaml github workflow

src/main/kotlin/no/nav/syfo/cronjob/dialogmotesvar/PublishDialogmotesvarService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ArbeidsgiverPublishedToKafkaAtQueries.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/ArbeidstakersvarPublishedToKafkaAtQueries.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/BehandlersvarPublishedToKafkaAtQueries.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmotesvar/PublishDialogmotesvarServiceSpek.kt
=> Use use to fix db connection issue

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/KafkaIdenthendelseConsumerConfig.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Tenker den kan vente til mandag med å gå ut 😊
=> Enable identhendelse updates in prod

src/main/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/DialogmeldingService.kt, src/main/kotlin/no/nav/syfo/dialogmelding/domain/DialogmeldingSvar.kt, src/main/kotlin/no/nav/syfo/dialogmelding/kafka/KafkaDialogmeldingDTO.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerBehandlerVarselSvarQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/domain/PMotedeltakerBehandlerVarselSvar.kt, src/test/kotlin/no/nav/syfo/brev/behandler/BehandlerVarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/DialogmoteSvarGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/GeneratePDialogmote.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/KafkaDialogmeldingDTOGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/PMotedeltakerBehandlerVarselGenerator.kt
Invalid motesvar will not be published on the motesvar kafka topic.
Co-authored-by: June Henriksen <june.henriksen2@nav.no>
=> Mark motesvar sent after mote is finished as invalid

src/main/resources/db/migration/V8_6__update_wrong_referat_3.sql
https://jira.adeo.no/browse/FAGSYSTEM-254196
=> Censor referat sent to wrong innbygger

build.gradle.kts
Må revertere: soap mot altinn funker ikke med den nye cxf-versjonen.
=> Revert "Fix snyk issues (#401)"

.github/workflows/dispatch.yaml, src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/application/cache/RedisStore.kt, src/main/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApi.kt, src/main/kotlin/no/nav/syfo/client/pdl/PdlClient.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt, src/test/kotlin/no/nav/syfo/client/person/adressebeskyttelse/AdressebeskyttelseClientSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/UserConstants.kt, src/test/kotlin/no/nav/syfo/testhelper/generator/PdlResponseGenerator.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/IsoppfolgingstilfelleMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/PdlMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/SyfobehandlendeenhetMock.kt, src/test/kotlin/no/nav/syfo/testhelper/mock/VeilederTilgangskontrollMock.kt
Støtter ikke-aktiv ident for arbeidstaker. Usikker på om vi trenger det samme for nærmeste leder.
=> Support inactive personident

build.gradle.kts, src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonResponse.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerQuery.kt, src/main/kotlin/no/nav/syfo/identhendelse/IdenthendelseService.kt, src/main/kotlin/no/nav/syfo/identhendelse/kafka/IdenthendelseConsumerService.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt
Små endringer på retry-logikken etter oppdagelsene som ble gjort i `syfobehandlendeenhet`. I tillegg oppdatere `updated_at`-feltet.
=> Unsubscribe and resubscribe on errors from topic

src/main/resources/db/migration/V8_7__update_wrong_referat_4.sql
Veileder sendte inn referat på feil person.
=> Remove content from møtereferat in db

src/main/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerVarselService.kt
Den defaulter til epost, Lisa ønsker SMS
=> Set preferert kanal for brukernotifikasjoner

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/test/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt
Restanse av: https://github.com/navikt/isdialogmote/pull/408
Må ha med tilfeller der veileder forandrer tid og sted.
=> Remove brukeroppgaver

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Mote was closed in Arena. Set mote to LUKKET and alert of the status change on kafka
=> Close mote without cancelling or sending referat.

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerVarselService.kt, src/main/kotlin/no/nav/syfo/brev/esyfovarsel/DialogmoteInnkallingArbeidstakerData.kt, src/main/kotlin/no/nav/syfo/cronjob/CronjobModule.kt, src/main/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjob.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmotedeltakerVarselJournalpostService.kt, src/main/kotlin/no/nav/syfo/dialogmote/ReferatJournalpostService.kt, src/main/kotlin/no/nav/syfo/dialogmote/VarselService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MotedeltakerArbeidstakerVarselQuery.kt, src/test/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/VarselServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
Add toggle to turn off utsending of varsler via `esyfovarsel` inside distribution cron job if it wll be  needed.
=> Add sending to reserverte via esyfovarsel

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
https://jira.adeo.no/browse/FAGSYSTEM-274162
=> Close outdated mote

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Ref https://jira.adeo.no/browse/FAGSYSTEM-282275
=> Lukk utdatert møte

src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt
Fiks for brukeroppgaver på møte var ikke slettet ved ferdistilling.
=> Add calling slettBrukeroppgaverPaMote() when ferdigstilling

.github/workflows/dependency-submission.yaml
Ref: https://sikkerhet.nav.no/docs/verktoy/dependabot#oppsett-gradle-buildgradlekts--buildgradle
=> Prøver ut gradle-dependency-submission for at Dependabot skal finne avhengigheter

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Ref https://jira.adeo.no/browse/FAGSYSTEM-288632 og https://jira.adeo.no/browse/FAGSYSTEM-288505
=> Lukk utdaterte møter

src/main/kotlin/no/nav/syfo/App.kt, src/main/kotlin/no/nav/syfo/application/ApplicationEnvironment.kt, src/main/kotlin/no/nav/syfo/testdata/reset/TestdataResetService.kt, src/main/kotlin/no/nav/syfo/testdata/reset/database/MoteQuery.kt, src/main/kotlin/no/nav/syfo/testdata/reset/kafka/KafkaTestdataResetConfig.kt, src/main/kotlin/no/nav/syfo/testdata/reset/kafka/TestdataResetConsumer.kt, src/test/kotlin/no/nav/syfo/testdata.reset/TestdataResetServiceSpek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestEnvironment.kt
- Starter bare consumer i dev-gcp
- Melding til reset-topic sendes fra isyfomock
=> Add testdata reset functionality

.nais/naiserator-dev.yaml, .nais/naiserator-prod.yaml
Vi erstatter tms-min-side-proxy med vår egen esyfo-proxy.
Kommer med ny PR om å slette tilgang til tms-min-side-proxy når vi har fått switchet over til egen app
=> Add inbound policy for esyfo-proxy

build.gradle.kts
See https://github.com/navikt/isdialogmote/security/dependabot/16
=> Fix vulnerability in avro

src/main/resources/db/migration/V9_06__update_wrong_referat.sql
https://jira.adeo.no/browse/FAGSYSTEM-313666
=> IS-1989: Remove referat with sensitive information

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Se Jira: https://jira.adeo.no/browse/FAGSYSTEM-314044#
~Tenkte vi ikke trengte møteliste fra cutoff, så gjorde det bare sånn 🤷🏼‍♂️~
=> IS-2005: Close duplicate meeting

src/main/kotlin/no/nav/syfo/application/api/ApiModule.kt, src/main/kotlin/no/nav/syfo/dialogmote/DialogmoteService.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteQuery.kt, src/main/kotlin/no/nav/syfo/dialogmote/database/MoteRepository.kt, src/test/kotlin/no/nav/syfo/dialogmote/database/MoteRepositorySpek.kt
- Lager `MoteRepository` som etterhvert kan bli erstatning for `MoteQuery`
=> IS-2060: Refactor select mote queries to repository class

src/main/resources/db/migration/V9_07__update_wrong_referat.sql
https://jira.adeo.no/browse/FAGSYSTEM-319639
Veileder holder på å skrive ny versjon av referatet, så denne kan merges litt senere i dag så unngår vi å skrive til databasen samtidig.
=> IS-2109: Clear referat with wrong text

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
https://jira.adeo.no/browse/FAGSYSTEM-315789
=> IS-2073: Lukk avholdt møte

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Møtet er allerede avholdt, og referat er sendt i andre kanaler.
https://jira.adeo.no/browse/FAGSYSTEM-322449
=> IS-2222: Lukk outdated mote

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Ref https://jira.adeo.no/browse/FAGSYSTEM-326785
=> IS-2308: Close mote

src/main/kotlin/no/nav/syfo/client/pdl/PdlPersonResponse.kt, src/test/kotlin/no/nav/syfo/client/pdl/PdHentlPersonSpek.kt
Se https://nav-it.slack.com/archives/C012X71FN04/p1714741805821889
Vi har sikkert denne feilen i flere apper også, men tror vi har fiksa i mange av de 🤔
=> IS-2351: Use correct capitalization for fullname

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Se Jirasak: https://jira.adeo.no/browse/FAGSYSTEM-329947
=> IS-2374: Close dialogmoter for no longer employed veileder

src/main/kotlin/no/nav/syfo/cronjob/dialogmoteOutdated/DialogmoteOutdatedCronjob.kt
Ref https://jira.adeo.no/browse/FAGSYSTEM-325306
=> IS-2388: Lukker to møter

build.gradle.kts
Prøver å oppdatere dependencies som nais console sier er sårbare.
Funker fint i dev og fjerner noen av sårbarhetene våre
=> IS-2756: Update vulnerable dependencies

src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederAccessServiceSpek.kt, src/test/kotlin/no/nav/syfo/client/azuread/AzureAdClientSpek.kt, src/test/kotlin/no/nav/syfo/client/dokarkiv/DokarkivClientSpek.kt, src/test/kotlin/no/nav/syfo/client/narmesteleder/NarmesteLederClientSpek.kt, src/test/kotlin/no/nav/syfo/client/person/kontaktinfo/KontaktinformasjonClientSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/database/repository/MoteRepositorySpek.kt, src/test/kotlin/no/nav/syfo/identhendelse/IdenthendelseServiceSpek.kt, src/test/kotlin/no/nav/syfo/janitor/JanitorServiceSpek.kt, src/test/kotlin/no/nav/syfo/testdata.reset/TestdataResetServiceSpek.kt
Fjerner unødvendig 
```
with(TestApplicationEngine()) {
start()
.....
}
```
fra tester som ikke gjør requester mot appens endepunkter
=> IS-2720: Remove unneccesary TestApplicationEngine

src/main/resources/db/migration/V9_10__update_wrong_referat.sql
https://jira.adeo.no/browse/FAGSYSTEM-363767
=> IS-3003: update wrong referat

src/test/kotlin/no/nav/syfo/application/api/PodApiSpek.kt, src/test/kotlin/no/nav/syfo/brev/arbeidstaker/ArbeidstakerBrevApiSpek.kt, src/test/kotlin/no/nav/syfo/brev/narmesteleder/NarmesteLederBrevSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/dialogmoteoutdated/DialogmoteOutdatedCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/journalforing/DialogmoteVarselJournalforingCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/journalpostdistribusjon/DialogmoteJournalpostDistribusjonCronjobSpek.kt, src/test/kotlin/no/nav/syfo/cronjob/statusendring/PublishDialogmoteStatusEndringCronjobSpek.kt, src/test/kotlin/no/nav/syfo/dialogmelding/DialogmeldingServiceSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/AvlysDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/FerdigstillDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/GetDialogmoteEnhetApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/OvertaDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2AllowVarselMedFysiskBrevSpek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/PostDialogmoteTidStedApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/TildelDialogmoteApiV2Spek.kt, src/test/kotlin/no/nav/syfo/dialogmote/api/v2/motestatusendring/GetDialogmoteStatusEndringApiV2Spek.kt, src/test/kotlin/no/nav/syfo/testhelper/TestApiUtils.kt
Migrert tester fra `with(TestApplicationEngine())` til `testApplication` for å kunne oppgradere til ktor3. 
Takk til copilot for god støtte :heart:
=> IS-2720: Migrate tests to testApplication

src/main/resources/db/migration/V9_11__update_wrong_referat.sql
Slettet møtereferat oppført på feil person. Noen bør nok dobbeltsjekke at dette blir korrekt.
=> IS-3015: Slettet møtereferat oppført på feil person

src/main/resources/db/migration/V9_12__update_wrong_referat.sql
Jira-sak: https://jira.adeo.no/browse/FAGSYSTEM-381714
Skal bare dobbeltsjekke rutinen med Stine før jeg merger.
=> IS-3284: Remove content in motereferat

src/main/resources/db/migration/V9_15__alter_table_narmeste_leder_navn_type.sql
Endrer type til `TEXT` for kolonnen `narmeste_leder_navn` i tabellen `mote_referat`
=> IS-2821: Endre kolonnetype til TEXT for narmeste_leder_navn
